/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package game.graphicalInterface;

import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author Mim
 */
@SuppressWarnings("unqualified-field-access")
public class TryToMove2 extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5253908339508463334L;
	/**
	 * Creates new form TryToMove2
	 */
	Point p;

	public TryToMove2() {
		this.p = new Point();
		initComponents();
	}

	@Override
	public void paint(final Graphics g) {
		super.paint(g);

		// define the position
		final int locX = MouseInfo.getPointerInfo().getLocation().x;
		final int locY = MouseInfo.getPointerInfo().getLocation().y;

		// draw a line (there is no drawPoint..)
		g.drawLine(locX, locY, locX, locY);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(51, 51, 0));

		jPanel1.setBackground(new java.awt.Color(51, 51, 0));

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 354, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 197, Short.MAX_VALUE));

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(36, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(70, 70, 70)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		/*
		 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
		 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
		 * ("Nimbus".equals(info.getName())) {
		 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
		 * } catch (ClassNotFoundException ex) {
		 * java.util.logging.Logger.getLogger(TryToMove2.class.getName()).log(
		 * java.util.logging.Level.SEVERE, null, ex); } catch
		 * (InstantiationException ex) {
		 * java.util.logging.Logger.getLogger(TryToMove2.class.getName()).log(
		 * java.util.logging.Level.SEVERE, null, ex); } catch
		 * (IllegalAccessException ex) {
		 * java.util.logging.Logger.getLogger(TryToMove2.class.getName()).log(
		 * java.util.logging.Level.SEVERE, null, ex); } catch
		 * (javax.swing.UnsupportedLookAndFeelException ex) {
		 * java.util.logging.Logger.getLogger(TryToMove2.class.getName()).log(
		 * java.util.logging.Level.SEVERE, null, ex); } //</editor-fold>
		 */

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new TryToMove2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
